### ISSUE TITLE
Add client options for configuring a connection pool

### ISSUE THREAD

**Issue by mcrumm** [dashbitco/broadway_sqs#40]
As we did for Cloud Pub/Sub (plataformatec/broadway_cloud_pub_sub#37), should we look to implement pipeline-specific connection pools for BroadwaySQS?

I was about to start on a PR for this when I realized it might be a little more involved than the Pub/Sub change, as we don't have a hard requirement on `:hackney` here.  Should we add one?

**Comment by msaraiva** [comment]
Not sure. I remember we've discussed some time ago that since broadway producers already work as a pool, the best approach would be to use something like Mint. I'm sceptical that adding these options now would bring any real benefit but I might be wrong. We would need some real benchmark to make sure :)

**Comment by josevalim** [comment]
So my recommendation is to use github.com/keathley/finch which is still a pool but without the extra copying. :)
