### ISSUE TITLE
Producer would sometimes send messages into the void

### ISSUE THREAD

**Issue by martosaur** [dashbitco/broadway_sqs#62]
I think there's a bug in a way producer [handles the demand](https://github.com/dashbitco/broadway_sqs/blob/master/lib/broadway_sqs/producer.ex#L214).

Consider following scenario:
1. Producer receives demand for `10` messages
2. Producer fetches `9` messages from the server [here](https://github.com/dashbitco/broadway_sqs/blob/master/lib/broadway_sqs/producer.ex#L240)
3. Producer then schedules an immediate `receive` [here](https://github.com/dashbitco/broadway_sqs/blob/master/lib/broadway_sqs/producer.ex#L247)
4. Producer sends `9` messages to a consumer [via return value of `handle_demand` callback](https://github.com/dashbitco/broadway_sqs/blob/master/lib/broadway_sqs/producer.ex#L215)
5. Scheduled on step 3 `handle_receive_messages` kicks in, fetches message number `10` from the queue and... returns it into nowhere, since it isn't called from within a `handle_demand` callback?

I am not familiar with SQS, but I'd assume this would delay processing of message number `10` for at least the value of visibility timeout

I wrote a test to reproduce the bug, please find it [here](https://github.com/martosaur/broadway_sqs/blob/autoreceive_messages_bug/test/broadway_sqs/producer_test.exs#L553)
Sorry for not providing a full fix, I don't quite understand how this feature was desgined to work.

**Comment by josevalim** [comment]
`handle_demand` is stateful. If the consumer asks for 10 and you deliver 9, then the producer should know it has 1 message pending to deliver, because the consumer won't ask for it again. All callbacks in GenStage allow you to deliver a message later. The reason why your test is failing is because you are matching on the wrong message here:

https://github.com/martosaur/broadway_sqs/blob/autoreceive_messages_bug/test/broadway_sqs/producer_test.exs#L570

If you change it to:

    assert_receive {:message_handled, 10, _}

which is the same format used above, then it all works.
